
default: testio

testio:	testio.s
	python3 turtleasm.py testio.s

test1: turtleasm.py test.s
	python3 turtleasm.py test.s

challenge1: challenges/challenge1.s
	python3 turtleasm.py challenges/challenge1.s

challenge2: challenges/challenge2.s
	python3 turtleasm.py challenges/challenge2.s
